### ISSUE TITLE
120x bitcoin: MAX_BLOCKS_IN_TRANSIT_PER_PEER

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#10]
https://github.com/sugarchain-project/sugarchain/blob/1f291dc3a990e7b431a80718f2d0828f04a77220/src/validation.h#L84-L85

try 120x

**Comment by cryptozeny** [comment]
https://github.com/barrystyle/UraniumX/commit/e9006438e1f6a676030a58ab510d3b9dfa083e21#diff-349fbb003d5ae550a2e8fa658e475880R90

![image](https://user-images.githubusercontent.com/37016180/70569826-05125a80-1bde-11ea-8d41-4f076d876417.png)

**Comment by cryptozeny** [comment]
https://github.com/ResistancePlatform/resistance-core/commit/4efff3000711cc414e76cd57f2e605762b6cc339

![image](https://user-images.githubusercontent.com/37016180/71310090-61ce0a80-2453-11ea-9b48-15bed158a651.png)

RES blocktime is 60 sec. 10x faster than BTC

**Comment by cryptozeny** [comment]
`16 * 120 = 1920`

**Comment by decryp2kanon** [comment]
fixed in #135
