### ISSUE TITLE
Less DNS seeds when connected to VPN

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/sugarchain#169]
- VPN:
```
Protocol:     UDP
Kill Switch:  Disabled
Country:      Japan
City:         Osaka
```

- Result:
0 or less seeds found. But without VPN it finds well.

**Comment by decryp2kanon** [comment]
it seems just an issue on PROTONVPN. so closing.

**Comment by Technetium1** [comment]
Proton has its own DNS service, which is likely the cause of the issue.

**Comment by decryp2kanon** [comment]
good to know
