### ISSUE TITLE
Sync time on Windows

### ISSUE THREAD

**Issue by Technetium1** [sugarchain-project/sugarchain#182]
Unfortunately, Windows API does not expose anything for time management... However in [Microsoft documentation](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings) you will find
`w32tm /resync /nowait /rediscover` to resync.  Since the service may not be started; it should be.

Possible solution: `net start w32time & w32tm /resync /nowait /rediscover`

This could be tried before raising an error https://github.com/sugarchain-project/sugarchain/blob/7db380d865d2725d82d4bcd25a35659503934034/src/timedata.cpp#L101-L107

Unfortunately this does not seem so trivial on Linux, as there are many different NTP services that may or may not be installed/available/configured by default, whereas Windows *always* has this service.

**Comment by decryp2kanon** [comment]
Network rules:
To prevent fraud and timestamp attacks, nodes should be within 70 seconds [24] of accurate internet time, or they will be banned.

i guess its windows bug.

https://github.com/sugarchain-project/sugarchain/blob/d2d13cacd9e7c2640a02e6392978a26df06f9eb8/src/timedata.h

**Comment by Technetium1** [comment]
Unsure why I've had this struggle with time drift, as I have it set to automatically set time in Windows. This was conceived as a workaround for manually syncing the clock when starting up. Conceptually this would ensure that all Windows users have the most accurate time possible. Are there any downsides to implementing aside from this being Windows only?

![image](https://user-images.githubusercontent.com/9877150/103298050-8eeabc80-49c7-11eb-877e-0374822aacf2.png)

**Comment by decryp2kanon** [comment]
check your time server. i guess it occurs only on windows which bug after windows update. disable automatic updates.

![add-ntp-server-windows10](https://user-images.githubusercontent.com/60179867/103434087-d8ddd780-4c3f-11eb-8948-2be0ca71a664.jpg)

**Comment by Technetium1** [comment]
Thanks great point, switched myself to NIST servers instead of the windows default, hope this helps!
