### ISSUE TITLE
Attempt to resolve IP when RPC ACL parsed

### ISSUE THREAD

**Issue by Technetium1** [sugarchain-project/sugarchain#183]
It might be extra effort to rebuild ACL if the IPs were to change after init, but it may be reasonable to attempt to resolve here with `LookupHost()`

https://github.com/sugarchain-project/sugarchain/blob/7db380d865d2725d82d4bcd25a35659503934034/src/httpserver.cpp#L173-L180

**Comment by decryp2kanon** [comment]
we never changed this part from btc. whats the current issue?

**Comment by Technetium1** [comment]
`rpcallowip=subdomain.example.com` will fail, even if there is a valid A record for the domain, as only IP/netmask is allowed there

**Comment by decryp2kanon** [comment]
try this format like `http://123.123.123.123:7777`
