### ISSUE TITLE
Unable to connect to the node to update the block

### ISSUE THREAD

**Issue by yeruisheng** [sugarchain-project/sugarchain#190]
About nine to ten days ago, my wallet could not connect to the node to update the block. After opening sugarchain-qt, it always showed that it was connecting to the node. I thought it was the reason for my wallet version. After the backup, I deleted the old version ( 16.3.34) I downloaded the latest version 16.3.36. I opened the sugarchain-qt system and prompted that the file was damaged. In desperation, I downloaded the version 16.3.34, but it couldn’t solve the problem. What should I do? I use OSX system @ldenman @casey @eklitzke @rion @diegoviola  @ldenman @casey @eklitzke @rion @diegoviola

**Comment by decryp2kanon** [comment]
try new version payapoya
