### ISSUE TITLE
The wallet crashes while syncing headers on 16GB ram i5 9400F

### ISSUE THREAD

**Issue by nickynine** [sugarchain-project/sugarchain#192]
The wallet crashes while syncing headers on 16GB ram i5 9400F

its goes up to 65 percent and the app crashes without a warning.

**Comment by lrhel** [comment]
Can you please re-run the wallet with the `-debug=1` flag on, then post the content of your `debug.log` ?

**Comment by nickynine** [comment]
> Can you please re-run the wallet with the `-debug=1` flag on, then post the content of your `debug.log` ?

Its proceeding after -debug=1 and run as admin. 
Thanks

**Comment by decryp2kanon** [comment]
what version? 0.16.3.36 or 0.21?
