### ISSUE TITLE
WIN: hide testnet icon

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#30]
hide testnet launch icon or change icon different style.

![Screenshot_20191219-112501_Discord](https://user-images.githubusercontent.com/37016180/71139737-61b2ec80-2252-11ea-9aaa-20df0e3edf73.jpg)

I found that some new users have synced testnet for two days

**Comment by Nugetzrul3** [comment]
Put testnet in a separate folder maybe? Or maybe create a dev release to include testnet, and a normal release without testnet

**Comment by cryptozeny** [comment]
since we use windows installer by BTC team (part of BTC) and we didn't made this. if we do, we have to change the installer.

**Comment by Nugetzrul3** [comment]
Does the installer use nsis?

**Comment by decryp2kanon** [comment]
since BTC do this way, we do not change. closing.
