### ISSUE TITLE
yespower compiler -O2

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#31]
https://github.com/ResistancePlatform/resistance-core/commit/f84f9d61d8dcec72e5e0c674d787ff70a060a053

```cpp
libbitcoin_common_a_CFLAGS = $(AM_CFLAGS) $(PIE_FLAGS) -O2
```

**Comment by solardiz** [comment]
I think the use of `-O1` by default was specific to Zcash, and you're probably already having this code built with `-O2` or higher.

**Comment by cryptozeny** [comment]
yeah, we have already
```
$(PIE_FLAGS) -Wall -O2 -fomit-frame-pointer
```
thanks!

https://github.com/sugarchain-project/sugarchain/blob/f09343a33ec39878e83ec2b4fd11409c5690cefa/src/Makefile.am#L260

**Comment by cryptozeny** [comment]
we should remove `-fomit-frame-pointer`?

**Comment by solardiz** [comment]
`-fomit-frame-pointer` improves performance a little bit, especially on 32-bit x86. Its only drawback is that it prevents debugging backtraces. You can keep it.

**Comment by cryptozeny** [comment]
thanks so much :smile:
