### ISSUE TITLE
during IBD report block numbers

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#32]
https://github.com/ResistancePlatform/resistance-core/commit/48e6c14779b0ca9b96a608aa5d18acc718f4bc12
https://github.com/ResistancePlatform/resistance-core/commit/6732897660d5cf2bcb9d6d1aa23766a26f71a135
https://github.com/ResistancePlatform/resistance-core/commit/21664027417361a2e4747265c506d0fef1c444df
https://github.com/ResistancePlatform/resistance-core/commit/75a437e9c571e2c2db380e1700f4d602679c7961

**Comment by solardiz** [comment]
That commit you referenced was further updated with the following 3 commits. You'll likely want to combine all four.

https://github.com/ResistancePlatform/resistance-core/commit/6732897660d5cf2bcb9d6d1aa23766a26f71a135
https://github.com/ResistancePlatform/resistance-core/commit/21664027417361a2e4747265c506d0fef1c444df
https://github.com/ResistancePlatform/resistance-core/commit/75a437e9c571e2c2db380e1700f4d602679c7961

There were even further updates to this code when merging Zcash's newer changes, but those are not relevant to you.

**Comment by decryp2kanon** [comment]
merged, but it display (partially) to debug when only QT mode
https://github.com/sugarchain-project/sugarchain/pull/128

**Comment by decryp2kanon** [comment]
fixed. closing
