### ISSUE TITLE
Yespower: don't use abort()

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#37]
https://github.com/ResistancePlatform/resistance-core/commit/64ee78a1f51c37bd87a2f46c652ff88b0f3f7e2b

https://github.com/sugarchain-project/sugarchain/blob/bf58fb236fc456d94665b15e77d492c6e1ef83f6/src/primitives/block.cpp#L24-L41

### my question:
solardiz suggested this `abort()` last year, but it seemed something is changed.

**Comment by cryptozeny** [comment]
https://stackoverflow.com/questions/397075/what-is-the-difference-between-exit-and-abort

**Comment by cryptozeny** [comment]
duplicated in https://github.com/sugarchain-project/sugarchain/issues/33

**Comment by cryptozeny** [comment]
i assume `abort` causes this
https://github.com/sugarchain-project/sugarchain/issues/43

**Comment by decryp2kanon** [comment]
fixed
