### ISSUE TITLE
Windows10: reindex after reboot

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/sugarchain#43]
KezToday at 9:42 PM
Guys, everytime I load the wallet, i need to resync entire chain. Any reason why?

@volbil#8559 right.
> it can be caused by node crash during shut down. Blockchain filed get corrupted and it triggers reindex.

@Kez#3857  did shut down his Windows10, but Yumekawa didn't hear the signal. so it was forced shut down. so blockdata didn't finalized. he had to reindex again after reboot. i had similar issue on BTC.

```
2019-12-29 18:08:02 Dumped mempool: 0s to copy, 0s to dump
2020-01-01 12:41:39 
```

Normal shutdown is like so: `Shutdown: done`
```
2020-01-01 13:02:24 Dumped mempool: 5e-06s to copy, 0.004548s to dump
2020-01-01 13:02:24 Shutdown: done
```

**Comment by decryp2kanon** [comment]
#61

**Comment by decryp2kanon** [comment]
#61 fixed
