### ISSUE TITLE
[PoW cache] wallet.dat recognize issue on Win64 after unexpected system shut down (ie: power outage)

### ISSUE THREAD

**Issue by cryptoanzu** [sugarchain-project/sugarchain#46]
wallet.dat cannot recognize on PoW cache version 
https://github.com/sugarchain-project/sugarchain/tree/v0.16.3.25rc1-6048eba

this issue occured only on Win64, but Linux64 is fine. i will investigate on this issue soon. not tested on OSX yet.

Win64: crashed
Linux64: fine
OSX: not tested

@volbil 

<details><summary>CLICK ME</summary>
<p>

![image](https://user-images.githubusercontent.com/37780124/72699795-237c5600-3b8d-11ea-9be2-7bedb88d3bb0.png)

</p>
</details>

**Comment by decryp2kanon** [comment]
#61 fixed
