### ISSUE TITLE
How to use Addressindex?

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/sugarchain#57]
![image](https://user-images.githubusercontent.com/60179867/73992350-3915bc00-4992-11ea-9115-b0cdfc513bb8.png)

i need some tutorial @volbil

**Comment by volbil** [comment]
I guess you have to run qt wallet with -addressindex flag, otherwise it won't work.

**Comment by decryp2kanon** [comment]
adding: `-txindex=1 -addressindex=1` works to me, but sometimes you may need `-reindex` flag

> ./src/sugarchaind -server=1 -rpcuser=rpcuser -rpcpassword=rpcpassword -testnet -txindex=1 -addressindex=1 -daemon
